<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="61507" started-at="2018-07-12T09:11:18Z" finished-at="2018-07-12T09:12:19Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="61507" started-at="2018-07-12T09:11:18Z" finished-at="2018-07-12T09:12:19Z">
      <class name="com.qait.automation.parallelone.NewTest">
        <test-method status="PASS" signature="before()[pri:0, instance:com.qait.automation.parallelone.NewTest@e25b2fe]" name="before" is-config="true" duration-ms="51235" started-at="2018-07-12T09:11:18Z" finished-at="2018-07-12T09:12:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method status="FAIL" signature="testinvalidlogin()[pri:0, instance:com.qait.automation.parallelone.NewTest@e25b2fe]" name="testinvalidlogin" duration-ms="215" started-at="2018-07-12T09:12:09Z" finished-at="2018-07-12T09:12:09Z">
          <exception class="java.lang.ClassCastException">
            <message>
              <![CDATA[com.qait.automation.parallelone.Superclass cannot be cast to com.qait.automation.parallelone.subclass2]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ClassCastException: com.qait.automation.parallelone.Superclass cannot be cast to com.qait.automation.parallelone.subclass2
at com.qait.automation.parallelone.NewTest.testinvalidlogin(NewTest.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ClassCastException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testinvalidlogin -->
        <test-method status="PASS" signature="testvalidlogin()[pri:0, instance:com.qait.automation.parallelone.NewTest@e25b2fe]" name="testvalidlogin" duration-ms="9696" started-at="2018-07-12T09:12:09Z" finished-at="2018-07-12T09:12:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testvalidlogin -->
      </class> <!-- com.qait.automation.parallelone.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
